version: "3"
services:
  queue-processor:
    image: queue-processor:latest
    container_name: queue-processor
    environment:
      - HOST_PATH=${HOST_PATH}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./unity-volume:/unity-volume
